### ISSUE TITLE
In blog search feature

### ISSUE THREAD

**Issue by rahuldotbiz** [reeseschultz/11r#4]
If there could be an search feature it would be easy to find posts .

**Comment by reeseschultz** [comment]
This is out of scope for the project, because there's too many ways to implement it. Take, for example, [the search functionality in the Eleventy documentation](https://www.11ty.dev/docs/search/). It uses DuckDuckGo, but somebody may prefer Google or Bing. Somebody could feasibly use their own Elasticsearch cluster or something too.

To make it more complicated, some people prefer JavaScript implementations with real-time search feedback, others prefer static form fields whether there is a client- or server-side backend.

While 11r is undoubtedly opinionated, it's not *that* opinionated. It's easy enough to change. I'm worried that with a search functionality, many would would outright tear it out or completely replace it.

I think the vast majority of 11r users are better off finding out how to implement the search feature that works best for them in their clone or fork.
