### ISSUE TITLE
Comment in post

### ISSUE THREAD

**Issue by rahuldotbiz** [reeseschultz/11r#5]
Adding comment feature is the main thing  because people comment on post. So adding disqus to the this amazing website will be cool.

**Comment by reeseschultz** [comment]
Again, like I mentioned in  #4, this is out of scope for the project, because there's too many ways to implement it.

Disqus is one option of many. There's also [gitment](https://github.com/imsun/gitment), for instance. Some people prefer Facebook comments. I think for users that know which system they want to use, it's pretty trivial to add a comment feature to a clone or fork of 11r.
